---
title: "Graphs"
author: "Carlos Sanchez"
date: "1/26/2021"
output: html_document
---

```{r}
url <- "https://raw.githubusercontent.com/Xiaodan/Coursera-Exploratory-Data-Analysis/master/data/avgpm25.csv"
pollution <- data.table::fread(url, colClasses = c("numeric", "character", "factor", "numeric", "numeric"))

```

```{r}
head(pollution)
summary(pollution)
```


```{r}
boxplot(pollution$pm25, col = "blue")
abline(h=12)
```



```{r}
hist(pollution$pm25, col = "green", breaks = 100)
abline(v=12, lwd = 2)
abline(v = median(pollution$pm25), col = "magenta", lwd = 4)
rug(pollution$pm25)
```

```{r}
barplot(table(pollution$region), col = "wheat", main ="Number of Counties in Each Region")
```


```{r}
boxplot(pm25 ~ region, data = pollution, col = "red")
```

```{r}
par(mfrow = c(2,1), mar = c(4,4,2,1))
hist(subset(pollution, region == "east")$pm25, col = "green")
hist(subset(pollution, region == "west")$pm25, col = "green")

```

```{r}
with(pollution, plot(latitude, pm25, col = region  ))
abline(h = 12, lwd = 2, lty = 2)
```

```{r}
par(mfrow = c(1,2), mar = c(5,4,2,1))
with(subset(pollution, region == "west"), plot(latitude, pm25, main = "West"))
with(subset(pollution, region == "east"), plot(latitude, pm25, main = "East"))

```



LATTICE

```{r}
library(lattice)
state <- data.frame(state.x77, region = state.region)
```

```{r}
xyplot(Life.Exp ~ Income | region, data = state, layout = c(4,1))
```


```{r}
library(ggplot2)

data(mpg)
qplot(displ, hwy, data = mpg)
```



BASE GRAPHICS

```{r}
library(datasets)
hist(airquality$Ozone)
```




```{r}
with(airquality, plot(Wind, Ozone))
title(main = "Ozone and Wind in NYC")
```


```{r}
airquality <- transform(airquality, Month = factor(Month))
boxplot(Ozone ~ Month, airquality, xlab = "Month", ylab = "Ozone (ppb)")
```


```{r}
with(airquality, plot(Wind, Ozone, main = "Ozone and Wind in NYC"))
with(subset(airquality, Month == 5), points(Wind, Ozone, col = "blue"))
```


```{r}
with(airquality, plot(Wind, Ozone, main = "Ozone and Wind in NYC", type = "n"))
with(subset(airquality, Month == 5), points(Wind, Ozone, col = "blue"))
with(subset(airquality, Month != 5), points(Wind, Ozone, col = "red"))
legend("topright", pch = 1, col = c("blue", "red"), legend = c("May", "Other Months"))
```


```{r}
with(airquality, plot(Wind, Ozone, main = "Ozone and Wind in NYC", pch = 20))
model <- lm (Ozone ~ Wind, airquality)
abline(model, lwd = 2)
```


```{r}
par(mfrow = c(1,2))
with(airquality, {
 plot(Wind, Ozone, main = "Ozone and Wind")
 plot(Solar.R, Ozone, main = "Ozone and Solar Radiation")
  
})
```


```{r}
par(mfrow = c(1,3), mar = c(4,4,2,1), oma = c(0,0,2,0))    #oma (outer margin)
with(airquality, {
 plot(Wind, Ozone, main = "Ozone and Wind")
 plot(Solar.R, Ozone, main = "Ozone and Solar Radiation")
 plot(Temp, Ozone, main = "Ozone and Temperature")
 mtext( "Ozone and Weather in New York City", outer = TRUE)
})
```


```{r}
example("points")
```



```{r}
x <- rnorm(100)
y <- rnorm(100)

plot(x,y, pch = 20, xlab = "Weigh", ylab = "Height")
title("Scatterplot")
text(-2, -2, "Label")
legend("topleft", legend = "Data", pch = 20)

fit <- lm(y ~ x)
abline(fit, col = "blue", lwd = 3)
```



```{r}
x <- rnorm(100)
y <- x  + rnorm(100)
g <- gl(2, 50, labels = c("Male", "Female"))

plot(x, y, type = "n")
points(x[g == "Male"], y[g == "Male"], col = "green")
points(x[g == "Female"], y[g == "Female"], col = "red")

```



```{r}

```



```{r}

```



```{r}

```



```{r}

```



```{r}

```



```{r}

```



```{r}

```













