---
title: "Lattice"
author: "Carlos Sanchez"
date: "1/29/2021"
output:
  pdf_document: default
  html_document: default
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

```{r}
library(lattice)

```


#LATTICE

```{r}
library(datasets)
xyplot(Ozone ~ Wind, data = airquality)

```

```{r}
airquality <- transform(airquality, Month = factor(Month))

xyplot(Ozone ~ Wind | Month, data = airquality, layout = c(5,1))

```



```{r}
p <- xyplot(Ozone ~ Wind, data = airquality)   #Nothing happens
print(p)
```


Lattice Panel Functions

```{r}
set.seed(10)
x <- rnorm(100)
f <- rep(0:1, each = 50)
y <- x + f - f * x + rnorm(100, sd = 0.5)
f <- factor(f, labels = c("Group 1", "Group 2"))
xyplot(y ~ x | f, layout = c(2,1))
```

```{r}
xyplot(y ~ x | f, panel = function(x, y, ...){
  panel.xyplot(x, y, ...)  #First call the default panel function for 'xyplot¡
  panel.abline(h = median(y), lty = 2)   #Add horizontal line
})

```

```{r}
xyplot(y ~ x | f, panel = function(x, y, ...){
  panel.xyplot(x, y, ...)
  panel.lmline(x, y, col = 2)
})

```


#GGPLOT2 (QPLOT)

```{r}
library(ggplot2)
str(mpg)
```

```{r}
qplot(displ, hwy, data = mpg)
```



```{r}
qplot(displ, hwy, data = mpg, color = drv)
```



```{r}
qplot(displ, hwy, data = mpg, geom = c("point", "smooth"))
```


```{r}
qplot(hwy, data = mpg, fill = drv)
qplot(y=hwy, data = mpg, color = drv)
```


```{r}
qplot(drv, hwy, data = mpg, geom = "boxplot")
qplot(drv, hwy, data = mpg, geom = "boxplot", color = manufacturer)

```



```{r}
qplot(displ, hwy, data = mpg, facets = . ~ drv)
```



```{r}
qplot(hwy, data = mpg, facets = drv ~ ., binwidth = 2)
```



```{r}
qplot(displ, data = mpg, geom = "density", color = drv)
```



```{r}
qplot(displ, hwy, data = mpg, shape = drv)
qplot(displ, hwy, data = mpg, facets = . ~ drv) + geom_smooth(method = "lm")
```



```{r}
qplot(displ, hwy, data = mpg, color = drv) + geom_smooth(method = "lm")

```


#GGPLOT2 (ggplot)

```{r}
# fileUrl <- "https://raw.githubusercontent.com/rdpeng/artofdatascience/master/manuscript/data/bmi_pm25_no2_sim.csv"
fileUrl <- "https://raw.githubusercontent.com/rdpeng/artofdatascience/master/manuscript/data/bmi_pm25_no2_sim.csv"
maacs <- read.csv(fileUrl)
```



```{r}
qplot(logpm25, NocturnalSympt, data = maacs,  facets = . ~ bmicat, geom = c("point", "smooth"), method ="lm")
```



```{r}
g <- ggplot(maacs, aes(logpm25, NocturnalSympt))
summary(g)
print(g)
```



```{r}
g + geom_point()

```



```{r}
g + geom_point() + geom_smooth()
g + geom_point() + geom_smooth(method = "lm")
```



```{r}
g + geom_point() + geom_smooth(method = "lm")

```



```{r}
g + geom_point() + facet_grid(. ~ bmicat) + geom_smooth(method = "lm") 
```



```{r}
g + geom_point(color = "steelblue", size = 4, alpha = 1/2)
```



```{r}
g + geom_point(aes(color = bmicat), size = 4, alpha = 1/2)  # we use aes because color is a variable not a constant value as before

```



```{r}
g + geom_point(aes(color = bmicat)) + labs(title = "MAACS Cohort") + labs(x = expression("log " * PMN[2.5]), y = "Nocturnal Symptoms")    #Same with + ggtitle("MAACS Cohort")
```



```{r}
g + geom_point(aes(color = bmicat), size = 4, alpha = 1/2) + geom_smooth(size = 4, linetype = 3, method = "lm", se = FALSE)  # se = standard error (grey area)
```


```{r}
g + geom_point(aes(color = bmicat), size = 4, alpha = 1/2) + theme_bw(base_family = "Times")

```


```{r}
g + geom_line()
g + geom_line() + ylim(0,2)  #points out of range (outliers) are deleted
g + geom_line() + coord_cartesian(ylim = c(0,2))   #plot all points and some are out of scale
```


```{r}
cutpoints <- quantile(maacs$logno2_new, seq(0, 1, length = 4))
maacs$no2dec <- cut(maacs$logno2_new, cutpoints)
```


```{r}
g <- ggplot(maacs, aes(logpm25, NocturnalSympt))

g + geom_point(alpha = 1/3) +
  facet_wrap(bmicat ~ no2dec, nrow = 2, ncol = 4) +
  geom_smooth(method = "lm", se = FALSE, col = "steelblue") +
  theme_bw(base_family = "Times", base_size = 10) +
  labs(x = expression("log " * PM[2.5])) +
  labs(y = "Nocturnal Symptoms") + 
  labs(title = "MAACS Cohort")

```

```{r}
g <- ggplot(mpg, aes(x=displ, y=hwy, color = factor(year)))
g + geom_point() + facet_grid(drv~cyl,margins=TRUE)+geom_smooth(method="lm",size=2,se=FALSE,color="black") + labs(x = "Displacement", y = "Highway Mileage", title = "Swirl Rules!")
```


```{r}
qplot(price, data = diamonds, binwidth = 18497/30, fill = cut)
qplot(price, data = diamonds, binwidth = 18497/30, color = cut)

```


```{r}
qplot(price, data = diamonds, geom = "density", color = cut)
```

```{r}
qplot(carat, price, data = diamonds, shape = cut)
qplot(carat, price, data = diamonds, color = cut)
qplot(carat, price, data = diamonds, color = cut) + geom_smooth(method = "lm")
qplot(carat, price, data = diamonds, color = cut, facets = .~cut) + geom_smooth(method = "lm")
```



```{r}
g <- ggplot(diamonds, aes(depth, price))
g + geom_point(alpha = 1/3)

```


```{r}
cutpoints <- quantile(diamonds$carat, seq(0,1,length = 4), na.rm = TRUE)
diamonds$car2 <- cut(diamonds$carat, cutpoints)
g <- ggplot(diamonds, aes(depth, price))
g + geom_point(alpha = 1/3) + facet_grid(cut~car2)
```


```{r}
g + geom_point(alpha = 1/3) + facet_grid(cut~car2) + geom_smooth(method = "lm", size = 3, color = "pink")
```


```{r}
ggplot(diamonds, aes(carat, price)) + geom_boxplot() + facet_grid(. ~ cut)
```


COLORS

```{r}
library(grDevices)
sample(colors(), 20)

```


```{r}
pal <- colorRamp(c("red", "blue"))
pal(0) #red
pal(1) #blue
pal(0.5) #50% each

pal(seq(0,1, len=6))
```



```{r}
p1 <- colorRampPalette(c("red", "blue"))
p1(2)

```


```{r}
x <- sample(1000)
y <- sample(1000)
plot(x,y, pch=19, col = rgb(0, .5, .5))

plot(x,y, pch=19, col = rgb(0, .5, .5, .3))
```


```{r}
library(RColorBrewer)
cols <- brewer.pal(3, "BuGn")

```










