---
title: "Air Pollution Case Study"
author: "Carlos Sanchez"
date: "2/4/2021"
output: pdf_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

```{r}
setwd("~/R courses/Exploratory_data/Week4")
zipFile <- "downloadedFile.zip"
if(!file.exists(zipFile)){
  fileUrl <- "https://github.com/csanchez1971/-Data_Science_Specialization/blob/master/04_ExploratoryAnalysis/CaseStudy/pm25_data.zip"
  download.file(url = fileUrl, destfile = zipFile, method = "curl")
}
unzip("pm25_data.zip")
   

```


```{r}
pm0 <- read.table("./pm25_data/RD_501_88101_1999-0.txt", comment.char = "#", header = FALSE, sep = "|", na.strings = "")
cnames <- readLines("./pm25_data/RD_501_88101_1999-0.txt", 1)
cnames <- strsplit(cnames, "|", fixed = TRUE)
names(pm0) <- make.names(cnames[[1]])    #make.names avoid having spaces on the variable names

pm1 <- read.table("./pm25_data/RD_501_88101_2012-0.txt", comment.char = "#", header = FALSE, sep = "|", na.strings = "")
cnames <- readLines("./pm25_data/RD_501_88101_2012-0.txt", 1)
cnames <- strsplit(cnames, "|", fixed = TRUE)
names(pm1) <- make.names(cnames[[1]])    #make.names avoid having spaces on the variable names

memory_required <- round(dim(pm1)[1] * dim(pm1)[2] * 8 / 2^20)  #in MB
```


```{r}
head(pm0)

```


```{r}
x0 <- pm0$Sample.Value
class(x0)
x1 <- pm1$Sample.Value
class(x1)
```


```{r}
str(x0)
summary(x0)
str(x1)
summary(x1)
```


```{r}
mean(is.na(x0))
```


```{r}
boxplot(x0,x1)
boxplot(log(x0), log(x1))
```


```{r}
summary(x1)
negative <- x1<0

sum(negative, na.rm = T)
mean(negative, na.rm = T)  #since que values are 0 and 1, mean equals to %
```


```{r}
dates <- pm1$Date
str(dates)

```


```{r}
dates <- as.Date(as.character(dates), "%Y%m%d")

```


```{r}
hist(dates, "month")

```

To see when the negative values occurs:

```{r}
hist(dates[negative], "month")

```


If we focus on a single state (NY):

```{r}
# site0 <- subset(pm1, State.Code ==36, c(County.Code, Site.ID))
site0 <- unique(subset(pm0, State.Code ==36, c(County.Code, Site.ID)))
site1 <- unique(subset(pm1, State.Code ==36, c(County.Code, Site.ID)))

```




```{r}
site0 <- paste(site0[,1], site0[,2], sep = ".")
site1 <- paste(site1[,1], site1[,2], sep = ".") #Merge county and site ID

```


```{r}
(both <- intersect(site0, site1))

```




```{r}
pm0$county.site <- with(pm0, paste(County.Code, Site.ID, sep = "."))
pm1$county.site <- with(pm1, paste(County.Code, Site.ID, sep = "."))

```


If now subset for NY and for the state.site that exist in both datasets:

```{r}
cnt0 <- subset(pm0, State.Code == 36 & county.site %in% both)
cnt1 <- subset(pm1, State.Code == 36 & county.site %in% both)

```



```{r}
head(cnt0)

```


Split the dataframe by monitor and check how many observation do we have


```{r}
sapply(split(cnt0, cnt0$county.site), nrow)
sapply(split(cnt1, cnt1$county.site), nrow)
```




```{r}
pm0sub <- subset(pm0, State.Code == 36 & County.Code == 63 & Site.ID ==2008)
pm1sub <- subset(pm1, State.Code == 36 & County.Code == 63 & Site.ID ==2008)
dim(pm0sub)
dim(pm1sub)
```




```{r}
dates1 <- pm1sub$Date
x1sub <- pm1sub$Sample.Value
dates1 <- as.Date(as.character(dates1), "%Y%m%d")
plot(dates1, x1sub)

```




```{r}
dates0 <- pm0sub$Date
x0sub <- pm0sub$Sample.Value
dates0 <- as.Date(as.character(dates0), "%Y%m%d")
plot(dates0, x0sub)

```




```{r}
par(mfrow = c(1,2))
plot(dates0, x0sub, pch = 19)
abline(h = median(x0sub, na.rm = T))
plot(dates1, x1sub, pch = 19)
abline(h = median(x1sub, na.rm = T))

```




```{r}
rng <- range(x0sub, x1sub, na.rm = T)

```




```{r}

par(mfrow = c(1,2))
plot(dates0, x0sub, pch = 19, ylim = rng)
abline(h = median(x0sub, na.rm = T))
plot(dates1, x1sub, pch = 19, ylim = rng)
abline(h = median(x1sub, na.rm = T))

```




```{r}
mean0 <- with(pm0, tapply(Sample.Value, State.Code, mean, na.rm =T))
str(mean0)
summary(mean0)

mean1 <- with(pm1, tapply(Sample.Value, State.Code, mean, na.rm =T))
str(mean1)
summary(mean1)
```


```{r}
d0 <-  data.frame(state = names(mean0), mean = mean0)
d1 <-  data.frame(state = names(mean1), mean = mean1)

head(d0)
head(d1)
```


T
```{r}
mrg <- merge(d0, d1, by = "state")
head(mrg)
```


```{r}
par(mfrow=c(1,1))
with(mrg, plot(rep(1999, 52), mrg[,2], xlim = c(1998, 2013)))
with(mrg, points(rep(2012, 52), mrg[,3], xlim = c(1998, 2013)))

segments(rep(1999, 52), mrg[,2], rep(2012, 52), mrg[,3])
```











