---
title: "Hireachical clustering"
author: "Carlos Sanchez"
date: "2/1/2021"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```


#HIERARCHICAL CLUSTERING

```{r}
set.seed(1234)
par(mar = c(0,0,0,0))
x <- rnorm(12, mean = rep(1:3, each = 4), sd = 0.2)
y <- rnorm(12, mean = rep(c(1,2,1), each = 4), sd = 0.2)

plot(x,y, col = "blue", pch = 19, cex = 2)
text(x + 0.05, y + 0.05, labels = as.character(1:12))
```


```{r}
dataFrame <- data.frame(x = x, y = y)
distxy <- dist(dataFrame)
hClustering <- hclust(distxy)
plot(hClustering)
plot(as.dendrogram(hClustering))
```


```{r}
set.seed(143)
dataMatrix <- as.matrix(dataFrame)[sample(1:12),]
heatmap(dataMatrix)

```

#K-MEANS

```{r}
kmeansObj <-  kmeans(dataFrame, centers = 3)
names(kmeansObj)

```


```{r}
kmeansObj$cluster

```


```{r}
par(mar = rep(0.2, 4))
plot(x,y, col = kmeansObj$cluster, pch = 19, cex = 2)
points(kmeansObj$centers, col = 1:3, pch = 3, cex = 3, lwd = 3)

```


```{r}
set.seed(1234)
dataMatrix <- as.matrix(dataFrame)[sample(1:12), ]
kmeansObj2 <- kmeans(dataMatrix, centers = 3)
par(mfrow = c(1,2), mar = c(2, 3, 0.1, 0.1))
image(t(dataMatrix)[, nrow(dataMatrix):1], yatx = "n")
image(t(dataMatrix)[, order(kmeansObj$cluster)], yatx = "n")
```



#PRINCIPAL COMPONENTS

```{r}
set.seed(12345)
par(mar = rep(0.2, 4))
dataMatrix <- matrix(rnorm(400), nrow = 40)
image(1:10, 1:40, t(dataMatrix)[, nrow(dataMatrix):1])
```


```{r}
heatmap(dataMatrix)
```


```{r}


```


```{r}


```

 
```{r}


```


```{r}


```


```{r}


```


```{r}


```


```{r}


```


```{r}


```

